# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - environment_setup/src/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - environment_setup/src/*

pool:
  vmImage: "ubuntu-latest"

# It contains the same variables than the parameters.json file that you would provide with the CLI.
variables:
  - group: mlops-neosoft-vg
  - name: WORKSPACE_SKU
    value: basic
  - templateFile: './environment_setup/src/main.bicep'

steps:
  # task : https://docs.microsoft.com/fr-fr/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops
  - task: AzureCLI@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az group create --name $(RESOURCE_GROUP) --location $(LOCATION)
        az deployment group create --resource-group $(RESOURCE_GROUP) --template-file $(templateFile) --parameters baseName=$(BASE_NAME) location=$(LOCATION) amlWorkspaceName=$(WORKSPACE_NAME) sku=$(WORKSPACE_SKU)
